### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by lifujie25** [Nolovenodie/emby-crx#12]
emby的docker版本，出现2个滚动大屏
<img width="903" alt="image" src="https://github.com/Nolovenodie/emby-crx/assets/136134135/cd9df5db-111b-450c-b1af-a4c9e3a13a3a">

**Comment by AjianYo** [comment]
不止docker，服务端都出现了多个首页轮播，我三个😮‍💨

**Comment by 2229614420** [comment]
> 不止docker，服务端都出现了多个首页轮播，我三个😮‍💨

![image](https://github.com/Nolovenodie/emby-crx/assets/66009942/a75f8b01-d402-4b70-bd8d-9e41e2e3420c)

这样修改一下main.js，就可以避免首页加载出多个轮播了

**Comment by AjianYo** [comment]
> > 不止docker，服务端都出现了多个首页轮播，我三个😮‍💨
> 
> ![image](https://user-images.githubusercontent.com/66009942/248637801-a75f8b01-d402-4b70-bd8d-9e41e2e3420c.png)
> 
> 这样修改一下main.js，就可以避免首页加载出多个轮播了

好的，感谢指导👍

**Comment by lifujie25** [comment]
发现这个大佬的这个比较慢，而且比较容易出问题，不兼容手机版。

我用另外一个大佬的修改，加载速度快，可以限制不显示小姐姐，手机兼容，需要的留邮箱，到时候发你

**Comment by lvfu** [comment]
> 发现这个大佬的这个比较慢，而且比较容易出问题，不兼容手机版。
> 
> 我用另外一个大佬的修改，加载速度快，可以限制不显示小姐姐，手机兼容，需要的留邮箱，到时候发你

想看看 2995333268@qq.com

**Comment by lifujie25** [comment]
![IMG_7879](https://github.com/Nolovenodie/emby-crx/assets/136134135/ad64b15c-a2d9-4666-ba18-cec32f9aa043)
手机版的，电脑版本就跟原来一样，只是微调了logo显示

**Comment by lvfu** [comment]
> > > 发现这个大佬的这个比较慢，而且比较容易出问题，不兼容手机版。
> > > 我用另外一个大佬的修改，加载速度快，可以限制不显示小姐姐，手机兼容，需要的留邮箱，到时候发你
> > 
> > 
> > 想看看 [2995333268@qq.com](mailto:2995333268@qq.com)
> 
> 你看看后面截图，看是否合适

感谢，我回家就试试

**Comment by z3shan33** [comment]
> 发现这个大佬的这个比较慢，而且比较容易出问题，不兼容手机版。
> 
> 我用另外一个大佬的修改，加载速度快，可以限制不显示小姐姐，手机兼容，需要的留邮箱，到时候发你

发来学习一下 z3shan33@163.com

**Comment by AjianYo** [comment]
> 发现这个大佬的这个比较慢，而且比较容易出问题，不兼容手机版。
> 
> 我用另外一个大佬的修改，加载速度快，可以限制不显示小姐姐，手机兼容，需要的留邮箱，到时候发你

hongye89819@gmail.com 感谢分享

**Comment by Nolovenodie** [comment]
可以提个pr，叫我瞅瞅怎么个事儿 :D

**Comment by zxiao777** [comment]
> 

大佬给我一个看看 2512002352@qq.com  谢谢

**Comment by zxiao777** [comment]
> 发现这个大佬的这个比较慢，而且比较容易出问题，不兼容手机版。
> 
> 我用另外一个大佬的修改，加载速度快，可以限制不显示小姐姐，手机兼容，需要的留邮箱，到时候发你
大佬给我一个看看 [2512002352@qq.com](mailto:2512002352@qq.com) 谢谢

**Comment by 929126387** [comment]
> > > 发现这个大佬的这个比较慢，而且比较容易出问题，不兼容手机版。
> > > 我用另外一个大佬的修改，加载速度快，可以限制不显示小姐姐，手机兼容，需要的留邮箱，到时候发你
> > 
> > 
> > 想看看 [2995333268@qq.com](mailto:2995333268@qq.com)
> 
> 你看看后面截图，看是否合适

929126387@qq.com

**Comment by Nolovenodie** [comment]
已修复

**Comment by yue631377105** [comment]
> 发现这个大佬的这个比较慢，而且比较容易出问题，不兼容手机版。
> 
> 我用另外一个大佬的修改，加载速度快，可以限制不显示小姐姐，手机兼容，需要的留邮箱，到时候发你

朋友，能否发一份试试，现在就差手机版的了

**Comment by yue631377105** [comment]
> > 发现这个大佬的这个比较慢，而且比较容易出问题，不兼容手机版。
> > 我用另外一个大佬的修改，加载速度快，可以限制不显示小姐姐，手机兼容，需要的留邮箱，到时候发你
> 
> 朋友，能否发一份试试，现在就差手机版的了

忘记留邮箱了，631377105@qq.com  ,谢谢！

**Comment by nanoia** [comment]
> 发现这个大佬的这个比较慢，而且比较容易出问题，不兼容手机版。
> 
> 我用另外一个大佬的修改，加载速度快，可以限制不显示小姐姐，手机兼容，需要的留邮箱，到时候发你

朋友你好，手机版看着效果很好，求一份文件试试，谢谢！ email base64：`c2h1aW1vdEBxcS5jb20=`

**Comment by jackloves111** [comment]
> 发现这个大佬的这个比较慢，而且比较容易出问题，不兼容手机版。
> 
> 我用另外一个大佬的修改，加载速度快，可以限制不显示小姐姐，手机兼容，需要的留邮箱，到时候发你


有没有仓库地址可以看看的，留邮箱还是不方便。@lifujie25
