### ISSUE TITLE
请问一下目前是按照什么规则来推轮播图的?

### ISSUE THREAD

**Issue by ericlokz** [Nolovenodie/emby-crx#19]
看了两天,没找到具体的规则..不像是最新入库的,也不像是高分的..而且只有电视剧库在推,电影之类都没有的?
感谢解答

**Comment by Nolovenodie** [comment]
就是最新入库

**Comment by ericlokz** [comment]
可我新入库了好几场新的剧集,也不能说完全没变化,也就1部进去了轮播,其余的都是刚安装完后就推出来的图.是要隔天才会更新吗?还是多少小时后才更新呢?

**Comment by erbukuawu** [comment]
把main.js里面的这串代码引号里面的内容SortBy: "ProductionYear, PremiereDate, SortName"改成DateCreated，即SortBy: "DateCreated"就能按最新入库轮播了
![image](https://github.com/Nolovenodie/emby-crx/assets/39191744/cf4053aa-2bcd-48dd-aef2-068a8376558f)
