### ISSUE TITLE
在后台/web/index.html#!/settings/homescreen.html页面会有遮罩层

### ISSUE THREAD

**Issue by CangShui** [Nolovenodie/emby-crx#2]
需要在main.js中排除该页面

<pre>

/* 插入Loading */
	static initLoading() {
        const url = "homescreen"; // 指定url关键字
        if (!window.location.href.includes(url)) {
		const load = `
		<div class="misty-loading">
			<h1>MISTY MEDIA</h1>
			<div class="mdl-spinner"><div class="mdl-spinner__layer mdl-spinner__layer-1"><div class="mdl-spinner__circle-clipper mdl-spinner__left"><div class="mdl-spinner__circle mdl-spinner__circleLeft"></div></div><div class="mdl-spinner__circle-clipper mdl-spinner__right"><div class="mdl-spinner__circle mdl-spinner__circleRight"></div></div></div></div>
		</div>
		`;
		$("body").append(load);
		}
	}
</pre>

**Comment by sunr1s6** [comment]
昨天更新都没解决么？

**Comment by sunr1s6** [comment]
昨天更新都没解决么？

**Comment by Nolovenodie** [comment]
昨天喝醉了, 刚醒, 现在修

**Comment by Nolovenodie** [comment]
修好了

**Comment by sunr1s6** [comment]
> 修好了

感谢
