### ISSUE TITLE
经常首页点进去刷不出资源画面

### ISSUE THREAD

**Issue by neverpepsi** [Nolovenodie/emby-crx#21]
经常点进去没有资源，反复三四次才能正常一次
其次，怎么正常删除这个美化插件
docker安装下怎么关闭悬停按钮显示媒体库名称?

**Comment by Nolovenodie** [comment]
https://github.com/Nolovenodie/emby-crx/issues/18#issuecomment-1650925072

名称显示请修改css文件，readme里有写
