### ISSUE TITLE
BUG反馈-顶部导航下滑显示问题

### ISSUE THREAD

**Issue by jackloves111** [Nolovenodie/emby-crx#22]
如果左侧栏打开的状态下，顶部导航栏下滑再上滑出现，会被遮盖，检查代码发现是这个CSS的问题
```
.view:not(.hide) .skinHeader, .skinHeader-withBackground.headroom-scrolling {
    width: 100%;
}
```
将这个宽度100%注释掉后，可以恢复！
![c5db1036-5419-447f-98d8-1ab6b868843a](https://github.com/Nolovenodie/emby-crx/assets/89971817/b986c90e-ba47-41bf-9854-b2d86f5d1c93)

**Comment by Juway111** [comment]
```
.view:not(.hide) .skinHeader, .skinHeader-withBackground.headroom-scrolling {
    width: auto;
}
```
按图添加自定义CSS可修复该问题！
![1586a52f-ae49-4f1b-9fcd-24f118bb8737](https://github.com/Nolovenodie/emby-crx/assets/89971817/d31a23e2-cf7f-4c02-b1a3-e4c180310931)
