### ISSUE TITLE
功能请求: 标签页后台禁用轮播

### ISSUE THREAD

**Issue by AjianNie** [Nolovenodie/emby-crx#27]
目前版本中, 即使标签页处于后台也会自动轮播, 这样当切换到该标签页时, 会快速切换多个封面图, 有点“鬼畜”, 有碍美观.
哪位佬能给加个“后台禁用轮播”或者“后台冻结”的类似功能?
或者稍微指点一下如何修改, 我自己琢磨一下?

**Comment by mobclix** [comment]
我的想法是滚屏前加个判断，判断url是home结尾应该就行

if(window.location.href.endsWith("home")){
    /*todo*/
}

**Comment by mobclix** [comment]
> > 我的想法是滚屏前加个判断，判断url是home结尾应该就行
> > if(window.location.href.endsWith("home")){if（window.location.href.endsWith（“home”））{ //todo 都 }
> 
> 你的意思是 在非首页时禁用轮播? 这确实算一个小方法,但其实我说的“后台”是指 “浏览器在后台时 或 标签页非活跃时”

if(window.location.href.endsWith("home")&&!document.hidden){
//todo
}

**Comment by jackloves111** [comment]
> 我的想法是滚屏前加个判断，判断url是home结尾应该就行
> 
> if(window.location.href.endsWith("home")){ //todo }

@mobclix 可以提个pull吗？大佬
