### ISSUE TITLE
无法在Edge浏览器上使用

### ISSUE THREAD

**Issue by JsaRut** [Nolovenodie/emby-crx#42]
![image](https://github.com/Nolovenodie/emby-crx/assets/89496854/ebc1a6a3-8bdd-4825-8213-ffdf8af75ece)

**Comment by JsaRut** [comment]
补充：该错误在Chrome也出现

**Comment by hppydes** [comment]
> ![image](https://private-user-images.githubusercontent.com/89496854/293527531-ebc1a6a3-8bdd-4825-8213-ffdf8af75ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNzYxODIsIm5iZiI6MTcwODI3NTg4MiwicGF0aCI6Ii84OTQ5Njg1NC8yOTM1Mjc1MzEtZWJjMWE2YTMtOGJkZC00ODI1LTgyMTMtZmZkZjhhZjc1ZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE3MDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NjBkZjk4YWViYTJiNTFlMzQzNzUxOTAxZWUwZmQ1NTc5MWNmYzg4OWRmYmI5MmY3Y2RkMGQxMmE3Mzk4YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7vR9L--xh201A4BQnGCLY-pq6-uHbpAOXjgVETekxEk)

浏览器问题，解决办法 将CRX文件后缀改为rar，解压到文件夹中，拓展开启开发者模式——加载解压缩的拓展，选择文件夹即可。
