### ISSUE TITLE
库不显示图片和名称

### ISSUE THREAD

**Issue by xingfanxia** [Nolovenodie/emby-crx#48]
![Monosnap xingfan-nas-core 2024-01-18 03-48-43](https://github.com/Nolovenodie/emby-crx/assets/8936233/ff5da28f-bdf4-4c39-a8ea-cffa438f6c38)
换了个用户又可以显示
![Monosnap xingfan-nas-core 2024-01-18 03-58-14](https://github.com/Nolovenodie/emby-crx/assets/8936233/37c843fb-d051-4647-8ec8-2d8c3a955945)

有大佬知道为什么吗..

**Comment by xingfanxia** [comment]
```
main.js:161 Uncaught TypeError: Cannot read properties of null (reading 'complete')
    at main.js:161:54
```

**Comment by xingfanxia** [comment]
这个block的报错
```
		// 只判断第一张海报加载完毕, 优化加载速度
		await new Promise((resolve, reject) => {
			let waitLoading = setInterval(() => {
				if (document.querySelector(".misty-banner-cover").complete) {
					clearInterval(waitLoading);
					resolve();
				}
			}, 16);
		});
```

**Comment by Nanako718** [comment]
<img width="1117" alt="image" src="https://github.com/Nolovenodie/emby-crx/assets/60038246/23951afa-835f-4cd8-8263-b89c83624084">
应该是用户设置里设置的问题

**Comment by xingfanxia** [comment]
> <img alt="image" width="1117" src="https://private-user-images.githubusercontent.com/60038246/297744520-23951afa-835f-4cd8-8263-b89c83624084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODMxMzIsIm5iZiI6MTcwNTU4MjgzMiwicGF0aCI6Ii82MDAzODI0Ni8yOTc3NDQ1MjAtMjM5NTFhZmEtODM1Zi00Y2Q4LTgyNjMtYjg5YzgzNjI0MDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzMDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkYThkMzljOWE3MzIzOWZiNDU4ZGRkNTc5MzY4ODQwYWNlMThlYTU3ZTk3NDhiMjU1YjcwNzI1Yjk4ZTg2YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.caJdLaTCfmCcVNu5aB-3x9qm4s0TBU824_jEw-V4_ZQ"> 应该是用户设置里设置的问题

原来如此 可以了 谢谢大佬
