### ISSUE TITLE
我的媒体鼠标移动上去时,没有选项了.

### ISSUE THREAD

**Issue by 277383761** [Nolovenodie/emby-crx#5]
本来是可以直接在我的媒体封面上鼠标移动上去即可显示右下角的三个小圆点的.点击后出现菜单.开启这个以后我的媒体这几个版块只提供了点击进入的选项了.

**Comment by Nolovenodie** [comment]
[Update 增加媒体库鼠标悬浮更多选项显示](https://github.com/Nolovenodie/emby-crx/commit/36e542d561b1d5ee86466cb4ff21319ce308cc63)
