### ISSUE TITLE
标题显示问题

### ISSUE THREAD

**Issue by jinghuashang** [Nolovenodie/emby-crx#59]
![4](https://github.com/Nolovenodie/emby-crx/assets/77230776/b3e501c3-12e2-485a-b56d-f62d43547ef2)
![c](https://github.com/Nolovenodie/emby-crx/assets/77230776/f1f2143e-2b81-4cb1-b8cb-bbc91d4f4501)

如图，部分番剧出现标题显示错乱

**Comment by JsaRut** [comment]
可能是番剧的元数据错误，点进详细有没有出错？

**Comment by jinghuashang** [comment]
详细页倒是没问题，就是单纯首页海报出现问题，根据测试会出现在刚建媒体库的时候，具体什么原因就不知道了，并且再后面就不会出现问题。（如果配置了域名，通过域名访问就是正常的，但是用ip就会出现海报和标题不符的情况）

**Comment by JsaRut** [comment]
> 详细页倒是没问题，就是单纯首页海报出现问题，根据测试会出现在刚建媒体库的时候，具体什么原因就不知道了，并且再后面就不会出现问题。（如果配置了域名，通过域名访问就是正常的，但是用ip就会出现海报和标题不符的情况）

不应该吧，我这边一点问题都没有
开调试模式看一下，应该能发现什么

**Comment by jinghuashang** [comment]
> > 详细页倒是没问题，就是单纯首页海报出现问题，根据测试会出现在刚建媒体库的时候，具体什么原因就不知道了，并且再后面就不会出现问题。（如果配置了域名，通过域名访问就是正常的，但是用ip就会出现海报和标题不符的情况）
> 
> 不应该吧，我这边一点问题都没有 开调试模式看一下，应该能发现什么

现在bug没法复现了，好像是恢复正常了，没遇到过这个问题了。
